config/routes.rb
Rails.application.routes.draw do
  resources :pagamentos
  resources :receitas
  resources :despesas
  root to: 'visitors#index'

end

app/models/despesa.rb
class Despesa < ActiveRecord::Base
end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
  belongs_to :despesa
end

app/models/receita.rb
class Receita < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/despesas_controller.rb
class DespesasController < ApplicationController
  before_action :set_despesa, only: [:show, :edit, :update, :destroy]

  # GET /despesas
  # GET /despesas.json
  def index
    @despesas = Despesa.all
  end

  # GET /despesas/1
  # GET /despesas/1.json
  def show
  end

  # GET /despesas/new
  def new
    @despesa = Despesa.new
  end

  # GET /despesas/1/edit
  def edit
  end

  # POST /despesas
  # POST /despesas.json
  def create
    @despesa = Despesa.new(despesa_params)

    respond_to do |format|
      if @despesa.save
        format.html { redirect_to @despesa, notice: 'Despesa was successfully created.' }
        format.json { render :show, status: :created, location: @despesa }
      else
        format.html { render :new }
        format.json { render json: @despesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /despesas/1
  # PATCH/PUT /despesas/1.json
  def update
    respond_to do |format|
      if @despesa.update(despesa_params)
        format.html { redirect_to @despesa, notice: 'Despesa was successfully updated.' }
        format.json { render :show, status: :ok, location: @despesa }
      else
        format.html { render :edit }
        format.json { render json: @despesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /despesas/1
  # DELETE /despesas/1.json
  def destroy
    @despesa.destroy
    respond_to do |format|
      format.html { redirect_to despesas_url, notice: 'Despesa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_despesa
      @despesa = Despesa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def despesa_params
      params.require(:despesa).permit(:nomedespesa, :datavencimento, :valor, :saldo)
    end
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_pagamento, only: [:show, :edit, :update, :destroy]

  # GET /pagamentos
  # GET /pagamentos.json
  def index
    @pagamentos = Pagamento.all
  end

  # GET /pagamentos/1
  # GET /pagamentos/1.json
  def show
  end

  # GET /pagamentos/new
  def new
    @pagamento = Pagamento.new
  end

  # GET /pagamentos/1/edit
  def edit
  end

  # POST /pagamentos
  # POST /pagamentos.json
  def create
    @pagamento = Pagamento.new(pagamento_params)

    respond_to do |format|
      if @pagamento.save
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully created.' }
        format.json { render :show, status: :created, location: @pagamento }
      else
        format.html { render :new }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pagamentos/1
  # PATCH/PUT /pagamentos/1.json
  def update
    respond_to do |format|
      if @pagamento.update(pagamento_params)
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @pagamento }
      else
        format.html { render :edit }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagamentos/1
  # DELETE /pagamentos/1.json
  def destroy
    @pagamento.destroy
    respond_to do |format|
      format.html { redirect_to pagamentos_url, notice: 'Pagamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagamento
      @pagamento = Pagamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagamento_params
      params.require(:pagamento).permit(:despesa_id, :formapagamento, :data, :valor)
    end
end

app/controllers/receitas_controller.rb
class ReceitasController < ApplicationController
  before_action :set_receita, only: [:show, :edit, :update, :destroy]

  # GET /receitas
  # GET /receitas.json
  def index
    @receitas = Receita.all
  end

  # GET /receitas/1
  # GET /receitas/1.json
  def show
  end

  # GET /receitas/new
  def new
    @receita = Receita.new
  end

  # GET /receitas/1/edit
  def edit
  end

  # POST /receitas
  # POST /receitas.json
  def create
    @receita = Receita.new(receita_params)

    respond_to do |format|
      if @receita.save
        format.html { redirect_to @receita, notice: 'Receita was successfully created.' }
        format.json { render :show, status: :created, location: @receita }
      else
        format.html { render :new }
        format.json { render json: @receita.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receitas/1
  # PATCH/PUT /receitas/1.json
  def update
    respond_to do |format|
      if @receita.update(receita_params)
        format.html { redirect_to @receita, notice: 'Receita was successfully updated.' }
        format.json { render :show, status: :ok, location: @receita }
      else
        format.html { render :edit }
        format.json { render json: @receita.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receitas/1
  # DELETE /receitas/1.json
  def destroy
    @receita.destroy
    respond_to do |format|
      format.html { redirect_to receitas_url, notice: 'Receita was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receita
      @receita = Receita.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receita_params
      params.require(:receita).permit(:nomereceita, :datavencimento, :valor, :saldo)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/helpers/receitas_helper.rb
module ReceitasHelper
end

app/views/despesas/_form.html.haml
= simple_form_for(@despesa) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nomedespesa, label: "Nomedespesa"
    = f.input :datavencimento, label: "Datavencimento"
    = f.input :valor, label: "Valor"
    = f.input :saldo, label: "Saldo"

  .form-actions
    = f.submit "Salvar"

app/views/despesas/edit.html.haml
%h1 Editing despesa

= render 'form'

= link_to 'Show', @despesa
\|
= link_to 'Back', despesas_path

app/views/despesas/index.html.haml
%h1 Listing despesas

%table
  %thead
    %tr
      %th Nomedespesa
      %th Datavencimento
      %th Valor
      %th Saldo
      %th
      %th
      %th

  %tbody
    - @despesas.each do |despesa|
      %tr
        %td= despesa.nomedespesa
        %td= despesa.datavencimento
        %td= despesa.valor
        %td= despesa.saldo
        %td= link_to 'Show', despesa
        %td= link_to 'Edit', edit_despesa_path(despesa)
        %td= link_to 'Destroy', despesa, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Despesa', new_despesa_path

app/views/despesas/new.html.haml
%h1 New despesa

= render 'form'

= link_to 'Back', despesas_path

app/views/despesas/show.html.haml
%p#notice= notice

%p
  %b Nomedespesa:
  = @despesa.nomedespesa
%p
  %b Datavencimento:
  = @despesa.datavencimento
%p
  %b Valor:
  = @despesa.valor
%p
  %b Saldo:
  = @despesa.saldo

= link_to 'Edit', edit_despesa_path(@despesa)
\|
= link_to 'Back', despesas_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav
  %li= link_to 'HOME', root_path
  %li= link_to 'despesas', despesas_path
  %li= link_to 'receitas', receitas_path
  = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Controlegasto'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Controlegasto'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pagamentos/_form.html.haml
= simple_form_for(@pagamento) do |f|
  = f.error_notification

  .form-inputs
    = f.association :despesa, label: "Nome"
    = f.input :formapagamento, label: "Formapagamento"
    = f.input :data, label: "Data"
    = f.input :valor, label: "Valor"

  .form-actions
    = f.submit "Salvar"

app/views/pagamentos/edit.html.haml
%h1 Editing pagamento

= render 'form'

= link_to 'Show', @pagamento
\|
= link_to 'Back', pagamentos_path

app/views/pagamentos/index.html.haml
%h1 Listing pagamentos

%table
  %thead
    %tr
      %th Despesa
      %th Formapagamento
      %th Data
      %th Valor
      %th
      %th
      %th

  %tbody
    - @pagamentos.each do |pagamento|
      %tr
        %td= pagamento.despesa.nomedespesa
        %td= pagamento.formapagamento
        %td= pagamento.data
        %td= pagamento.valor
        %td= link_to 'Show', pagamento
        %td= link_to 'Edit', edit_pagamento_path(pagamento)
        %td= link_to 'Destroy', pagamento, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pagamento', new_pagamento_path

app/views/pagamentos/new.html.haml
%h1 New pagamento

= render 'form'

= link_to 'Back', pagamentos_path

app/views/pagamentos/show.html.haml
%p#notice= notice

%p
  %b Despesa:
  = @pagamento.despesa
%p
  %b Formapagamento:
  = @pagamento.formapagamento
%p
  %b Data:
  = @pagamento.data
%p
  %b Valor:
  = @pagamento.valor

= link_to 'Edit', edit_pagamento_path(@pagamento)
\|
= link_to 'Back', pagamentos_path

app/views/receitas/_form.html.haml
= simple_form_for(@receita) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nomereceita, label: "Nomereceita"
    = f.input :datavencimento, label: "Datavencimento"
    = f.input :valor, label: "Valor"
    = f.input :saldo, label: "Saldo"

  .form-actions
    = f.submit "Salvar"

app/views/receitas/edit.html.haml
%h1 Editing receita

= render 'form'

= link_to 'Show', @receita
\|
= link_to 'Back', receitas_path

app/views/receitas/index.html.haml
%h1 Listing receitas

%table
  %thead
    %tr
      %th Nomereceita
      %th Datavencimento
      %th Valor
      %th Saldo
      %th
      %th
      %th

  %tbody
    - @receitas.each do |receita|
      %tr
        %td= receita.nomereceita
        %td= receita.datavencimento
        %td= receita.valor
        %td= receita.saldo
        %td= link_to 'Show', receita
        %td= link_to 'Edit', edit_receita_path(receita)
        %td= link_to 'Destroy', receita, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Receita', new_receita_path

app/views/receitas/new.html.haml
%h1 New receita

= render 'form'

= link_to 'Back', receitas_path

app/views/receitas/show.html.haml
%p#notice= notice

%p
  %b Nomereceita:
  = @receita.nomereceita
%p
  %b Datavencimento:
  = @receita.datavencimento
%p
  %b Valor:
  = @receita.valor
%p
  %b Saldo:
  = @receita.saldo

= link_to 'Edit', edit_receita_path(@receita)
\|
= link_to 'Back', receitas_path

app/views/visitors/index.html.erb
<h3>Welcome</h3>